### ISSUE TITLE
Resurrect inputs

### ISSUE THREAD

**Issue by ganong123** [ganong-noel/ui_automatic_triggers#2]
Objective:
> Generate sourcing that is still needed

### data sourced successfully

`SAHMREALTIME.csv`: committed by Roshan [here](https://github.com/ganong-noel/ui_policy_2021/blob/main/analysis/input/SAHMREALTIME.csv), this almost certainly is from [here](https://fred.stlouisfed.org/series/SAHMREALTIME)
`realtime-TUR.csv`: This was hand entered from archived BLS releases. 
`ststdsadata.xlsx`: https://www.bls.gov/web/laus/ststdsadata.zip 
`state-jolts.dta`: [analysis/sources/loadjolts.do ](https://github.com/ganong-noel/ui_policy_2021/blob/issue_62_repkit/analysis/source/loadjolts.do)

### data sourcing needed
`simulation_covid_fullcps_collapsed_states.dta`: created by John C
`crck_ui_macro_dataset_weekly.dta`: from Chodorow-Reich, Coglianese, and Karabarbounis, QJE 2019

**Comment by ganong123** [comment]
@gabecr can you please write a sourcing note and/or commit code that generates the last two `dta` files. Thanks!

@nwuthenow please log results in the README

**Comment by gabecr** [comment]
Yes, but can you give me more direction on a sourcing note?  Where do I put
it and do you have an example?

**Comment by nwuthenow** [comment]
@gabecr The files that @ganong123 is referring to are
- `simulation_covid_fullcps_collapsed_states.dta` which are the state-level simulation for 1996m12-2021m12 that you linked to the first time in [this comment](https://github.com/ganong-noel/ui_policy_2021/issues/51#issuecomment-869667156) in June last year
- `crck_ui_macro_dataset_weekly.dta` which @ganong123 noted coming from Chodorow-Reich, Coglianese, and Karabarbounis, QJE 2019, but maybe you can confirm?  A screenshot of the first variables and rows is below. [This file is used for the tiered model creation.](https://github.com/ganong-noel/ui_automatic_triggers/blob/a185641a8137d782fcce4059a5b996a812de154a/analysis/source/tiered_model_creation.R#L21)
![image](https://user-images.githubusercontent.com/66383995/167168741-1f0dd1dc-aecd-4fd8-a08b-e8fedbed2a95.png)


------------------------

@ganong123 I uploaded a [`README.md`](https://github.com/ganong-noel/ui_automatic_triggers/blob/698bf36cb62ad9a79897fcf019688542162737ef/README.md) to this repo. It needs revision after @gabecr answers to the two points above, but does it look good to you otherwise, or should I change something?

**Comment by gabecr** [comment]
Thanks.  The description of crck_ui_macro_dataset_weekly.dta is fine.
For simulation_covid_fullcps_collapsed_states.dta, how about: Based on
Chodorow-Reich and Coglianese, JPubE 2021. See source/simulate_cpshistories
for additional detail.

**Comment by nwuthenow** [comment]
Perfect, thanks! @ganong123 I've updated the readme accordingly, and I'm running the full code on the RCC over the weekend. But I think otherwise the repo is ready for submission.
